//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeInsurance
    {
        public int HInsuranceID { get; set; }
        public string Property_Address { get; set; }
        public string Property_Value { get; set; }
        public System.DateTime Lease { get; set; }
        public string Legal_Owner { get; set; }
        public string Owner_Contact { get; set; }
        public string Owner_Email { get; set; }
        public double CoverageAmount { get; set; }
        public bool IsApproverd { get; set; }
        public int PolicyID { get; set; }
    
        public virtual Policies Policies { get; set; }
    }
}
