//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceManagementEntities : DbContext
    {
        public InsuranceManagementEntities()
            : base("name=InsuranceManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<LifeInsurance> LifeInsurance { get; set; }
        public virtual DbSet<Policies> Policies { get; set; }
        public virtual DbSet<TravelInsurance> TravelInsurance { get; set; }
        public virtual DbSet<CarInsurance> CarInsurance { get; set; }
        public virtual DbSet<HomeInsurance> HomeInsurance { get; set; }
    }
}
