//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class LifeInsurance
    {
        public int LInsuranceID { get; set; }
        public string Height_cm { get; set; }
        public string Weight_kg { get; set; }
        public string NHSNumber { get; set; }
        public string Health_Issues { get; set; }
        public string Income { get; set; }
        public string Benefitiary { get; set; }
        public string Relationship_B { get; set; }
        public double CoverageAmount { get; set; }
        public bool Year_10 { get; set; }
        public bool Year_20 { get; set; }
        public bool Year_30 { get; set; }
        public bool Univesal { get; set; }
        public bool Whole { get; set; }
        public bool Variable { get; set; }
        public bool Family { get; set; }
        public bool Debt { get; set; }
        public bool Estate { get; set; }
        public bool Business { get; set; }
        public bool Gaurantee { get; set; }
        public bool Unemployed { get; set; }
        public bool Self_E { get; set; }
        public bool Employee { get; set; }
        public bool IsApproverd { get; set; }
        public Nullable<int> PolicyID { get; set; }
    
        public virtual Policies Policies { get; set; }
    }
}
