//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Policies()
        {
            this.LifeInsurance1 = new HashSet<LifeInsurance>();
            this.TravelInsurance1 = new HashSet<TravelInsurance>();
            this.CarInsurance1 = new HashSet<CarInsurance>();
            this.HomeInsurance1 = new HashSet<HomeInsurance>();
        }
    
        public int PolicyID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool CarInsurance { get; set; }
        public bool HomeInsurance { get; set; }
        public bool LifeInsurance { get; set; }
        public bool TravelInsurance { get; set; }
        public double PremiumAmount { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LifeInsurance> LifeInsurance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelInsurance> TravelInsurance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarInsurance> CarInsurance1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeInsurance> HomeInsurance1 { get; set; }
    }
}
