//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravelInsurance
    {
        public int TInsuranceID { get; set; }
        public string Destination { get; set; }
        public System.DateTime TravelDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public string InternationalContactNumber { get; set; }
        public double CoverageAmount { get; set; }
        public bool LostBags { get; set; }
        public bool LegalCosts { get; set; }
        public bool EmergencyMedicalExpenses { get; set; }
        public bool CancellationCost { get; set; }
        public bool Single { get; set; }
        public bool Solo { get; set; }
        public bool European { get; set; }
        public bool Annual { get; set; }
        public bool Family { get; set; }
        public bool Summer { get; set; }
        public bool Gap { get; set; }
        public bool Worldwide { get; set; }
        public bool Winter { get; set; }
        public bool IsApproverd { get; set; }
        public int PolicyID { get; set; }
    
        public virtual Policies Policies { get; set; }
    }
}
